export const TASKS_ADD_SUCCESS = 'TASKS_ADD_SUCCESS';
export const TASKS_ADD_FAILURE = 'TASKS_ADD_FAILURE';
export const TASKS_RESET_VALIDATION = 'TASKS_RESET_VALIDATION';
export const TASKS_LOADED = 'TASKS_LOADED';
export const TASKS_UPDATED = 'TASKS_UPDATED';
